// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thoklhjtcmkdtufbpulb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRob2tsaGp0Y21rZHR1ZmJwdWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Nzc2MTUsImV4cCI6MjA3MDU1MzYxNX0.FknhO366LYdTuR6uvzU0Tn4C1bX_x3D9bKHZYhA_mYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});